yarnPath: ".yarn/releases/yarn-berry.js"

packageExtensions:
  "@tinacms/icons@0.24.0":
    peerDependencies:
      react: ^16.13.0
  "@tinacms/styles@0.24.0":
    peerDependencies:
      react: ^16.13.0
      "react-is": "^16.7.0" # react-is is a peerDependency of styled-components, so it's required pretty much everywhere
  "react-dismissible@*":
    peerDependencies:
      react: ^16.13.0
  "react-color@*": # https://github.com/casesandberg/react-color/pull/658
    peerDependencies:
      react: ^16.13.0
  "reactcss@*": # Same author, no PR yet - https://github.com/casesandberg/reactcss/issues?q=peerDependencies
    peerDependencies:
      react: ^16.13.0
  "react-beautiful-dnd@*":
    peerDependencies:
      react-dom: ^16.13.0
  "@tinacms/fields@0.24.0":
    peerDependencies:
      react: ^16.13.0
      "@tinacms/form-builder": "0.24.0"
      "@tinacms/icons": "0.24.0"
      "@tinacms/react-core": "0.24.0"
      "@tinacms/react-forms": "0.24.0"
      "@tinacms/styles": "0.24.0"
      "react-beautiful-dnd": "^11.0.5" #
      "final-form": "^4.18.2" # https://github.com/tinacms/tinacms/blob/859b8db0eb7cc63825e51bff0a1d024e5398135c/packages/@tinacms/forms/package.json#L35
      "react-is": "^16.7.0"
  "@tinacms/react-toolbar@0.24.0": # this is listed property for this package
    peerDependencies:
      react-dom: ^16.13.0
      "react-beautiful-dnd": "^11.0.5"
      "final-form": "^4.18.2" # https://github.com/tinacms/tinacms/blob/859b8db0eb7cc63825e51bff0a1d024e5398135c/packages/@tinacms/forms/package.json#L35
      "react-is": "^16.7.0"
  "@tinacms/react-forms@0.24.0":
    peerDependencies:
      "prop-types": ">=15"
      "final-form": "^4.18.2" # https://github.com/tinacms/tinacms/blob/859b8db0eb7cc63825e51bff0a1d024e5398135c/packages/@tinacms/forms/package.json#L35
      "react-is": "^16.7.0"
  "@tinacms/form-builder@0.24.0":
    peerDependencies:
      "final-form": "^4.18.2" # https://github.com/tinacms/tinacms/blob/859b8db0eb7cc63825e51bff0a1d024e5398135c/packages/@tinacms/forms/package.json#L35
      "react-is": "^16.7.0"
  "@tinacms/react-screens@*":
    peerDependencies:
      "react-is": "^16.7.0"
  "@tinacms/react-sidebar@*":
    peerDependencies:
      "final-form": "^4.18.2" # https://github.com/tinacms/tinacms/blob/859b8db0eb7cc63825e51bff0a1d024e5398135c/packages/@tinacms/forms/package.json#L35
      "react-is": "^16.7.0"
  "@tinacms/react-modals@*":
    peerDependencies:
      "react-is": "^16.7.0"
  "@tinacms/react-alerts@*":
    peerDependencies:
      "react-is": "^16.7.0"
  "babel-plugin-styled-components@*":
    peerDependencies:
      "react-is": "^16.7.0"
  tinacms@0.24.0:
    dependencies:
      "react-beautiful-dnd": "^11.0.5"
      "prop-types": ">=15"
      "final-form": "^4.18.2" # https://github.com/tinacms/tinacms/blob/859b8db0eb7cc63825e51bff0a1d024e5398135c/packages/@tinacms/forms/package.json#L35
      "react-is": "^16.7.0"
    peerDependencies:
      "react-is": "^16.7.0"
